name: deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - run: npm install -g bun

      - uses: actions/checkout@v2

      - run: bun install
      - run: bun run build
        env:
          NODE_ENV: production

      - uses: actions/upload-pages-artifact@v2
        with:
          path: "build"
